#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF
SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Starts the ksqlDB client

DEFAULT
   ./$EXECUTABLE
EOF
   exit
fi

docker exec -it debezium_ksql_kafka-ksql-cli-1 ksql http://ksqldb-server:8088
